# comentario -> para executar digite make 

all: compile
	
compile:

	gcc -o fork Fork.c	
	gcc -o pthread Pthread.c
	gcc -o 13 0size_of_var.c
	
	@echo "Compilaçao concluida"



clean:
	rm -rf *.out
	rm -rf ? 
	rm -rf ??
	
limpa:
	clear




